from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class RAGMode(str, Enum):
    FAST = "fast"
    SMART = "smart"


class RAGQueryRequest(BaseModel):
    owner: str = Field(..., description="Repository owner")
    repo: str = Field(..., description="Repository name")
    platform: str = Field(
        "github", description="Code hosting platform (github, gitlab, etc.)"
    )
    mode: RAGMode = Field(
        RAGMode.FAST, description='RAG mode: "fast" (default) or "smart"'
    )
    question: str = Field(..., description="User question about the repository")


class RAGAnswerData(BaseModel):
    answer: str = Field(..., description="Final answer generated by RAG")
    sources: List[str] = Field(
        ..., description="Referenced document sources used to generate the answer"
    )


class RAGStreamStepData(BaseModel):
    answer: str = Field(
        ...,
        description="Latest partial / final answer text (may be empty in early steps)",
    )
    delta: Optional[str] = Field(
        None,
        description="Incremental token for streaming output. When present, frontend should append this to the current answer instead of replacing.",
    )
    node: Optional[str] = Field(
        ...,
        description='Current RAG node name, e.g. "Intent", "Rewrite", "Retrieve", "Judge", "Generate"',
    )
    sources: List[str] = Field(
        ..., description="Accumulated referenced document sources up to this step"
    )
